title: Aka.ms/mcmultiplayerhelp – Microsoft account multiplayer settings
theme: jekyll-theme-cayman
google_analytics: UA-277903939-1
description: <a href="https://akamsmcmultiplayerhelp.github.io/"><img src="/gget.png"alt="Aka.ms/mcmultiplayerhelp"/></a>
